### ISSUE TITLE
CI/CD: Directed Acyclic Graphs aka job needs

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-advanced-training#12]
- Extend the explanation slides, https://docs.gitlab.com/ee/ci/directed_acyclic_graph/
- Create a lab with a template for
   - 2 stages
   - 2 jobs in each stage
   - 1st stage
      - 1 job puts sleep(60s)
      - 2nd job returns immediately
   - 2nd stage
      - 1 job just runs a bit
      - 2nd job could run immediately after the first stage 2nd job
   - Let the blocked pipeline run
   - Add the `needs` keyword to the 2nd stage 2nd job pointing to 1st stage 2nd job
   - Run it and explain the behaviour

```
stages:
  - build
  - test

build-rhel:
  stage: build
  script:
     - sleep(60)

build-deb:
   stage: build
   script:
      - exit 0

test-rhel:
   stage: test
   script:
      - sleep(60)

test-deb
   stage: test
   # needs: [ "build-deb" ]
   script:
      - exit 0
```
